







INSERT INTO cv (name) VALUES ('pub type');
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:computer file');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'computer file',(select dbxref_id from dbxref where accession='pub type:computer file'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:curator');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'curator',(select dbxref_id from dbxref where accession='pub type:curator'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:publication');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'publication',(select dbxref_id from dbxref where accession='pub type:publication'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:Book');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'Book',(select dbxref_id from dbxref where accession='pub type:Book'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:DNA/RNA sequence record');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'DNA/RNA sequence record',(select dbxref_id from dbxref where accession='pub type:DNA/RNA sequence record'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:abstract');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'abstract',(select dbxref_id from dbxref where accession='pub type:abstract'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:archive');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'archive',(select dbxref_id from dbxref where accession='pub type:archive'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:automatic genome annotation');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'automatic genome annotation',(select dbxref_id from dbxref where accession='pub type:automatic genome annotation'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:bibliographic list');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'bibliographic list',(select dbxref_id from dbxref where accession='pub type:bibliographic list'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:biography');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'biography',(select dbxref_id from dbxref where accession='pub type:biography'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:book');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'book',(select dbxref_id from dbxref where accession='pub type:book'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:book review');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'book review',(select dbxref_id from dbxref where accession='pub type:book review'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:booklet');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'booklet',(select dbxref_id from dbxref where accession='pub type:booklet'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:conference report');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'conference report',(select dbxref_id from dbxref where accession='pub type:conference report'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:curated genome annotation');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'curated genome annotation',(select dbxref_id from dbxref where accession='pub type:curated genome annotation'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:demonstration');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'demonstration',(select dbxref_id from dbxref where accession='pub type:demonstration'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:editorial');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'editorial',(select dbxref_id from dbxref where accession='pub type:editorial'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:erratum');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'erratum',(select dbxref_id from dbxref where accession='pub type:erratum'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:film');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'film',(select dbxref_id from dbxref where accession='pub type:film'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:interview');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'interview',(select dbxref_id from dbxref where accession='pub type:interview'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:jigsaw puzzle');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'jigsaw puzzle',(select dbxref_id from dbxref where accession='pub type:jigsaw puzzle'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:letter');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'letter',(select dbxref_id from dbxref where accession='pub type:letter'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:meeting report');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'meeting report',(select dbxref_id from dbxref where accession='pub type:meeting report'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:microfiche');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'microfiche',(select dbxref_id from dbxref where accession='pub type:microfiche'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:microscope slides');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'microscope slides',(select dbxref_id from dbxref where accession='pub type:microscope slides'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:news article');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'news article',(select dbxref_id from dbxref where accession='pub type:news article'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:note');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'note',(select dbxref_id from dbxref where accession='pub type:note'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:obituary');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'obituary',(select dbxref_id from dbxref where accession='pub type:obituary'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:other');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'other',(select dbxref_id from dbxref where accession='pub type:other'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:patent');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'patent',(select dbxref_id from dbxref where accession='pub type:patent'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:personal communication');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'personal communication',(select dbxref_id from dbxref where accession='pub type:personal communication'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:poem');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'poem',(select dbxref_id from dbxref where accession='pub type:poem'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:press release');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'press release',(select dbxref_id from dbxref where accession='pub type:press release'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:protein sequence record');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'protein sequence record',(select dbxref_id from dbxref where accession='pub type:protein sequence record'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:recording');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'recording',(select dbxref_id from dbxref where accession='pub type:recording'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:retraction');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'retraction',(select dbxref_id from dbxref where accession='pub type:retraction'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:review');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'review',(select dbxref_id from dbxref where accession='pub type:review'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:slides');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'slides',(select dbxref_id from dbxref where accession='pub type:slides'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:spoof');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'spoof',(select dbxref_id from dbxref where accession='pub type:spoof'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:stock list');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'stock list',(select dbxref_id from dbxref where accession='pub type:stock list'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:supplementary material');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'supplementary material',(select dbxref_id from dbxref where accession='pub type:supplementary material'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:tactile diagram');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'tactile diagram',(select dbxref_id from dbxref where accession='pub type:tactile diagram'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:teaching note');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'teaching note',(select dbxref_id from dbxref where accession='pub type:teaching note'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:thesis');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'thesis',(select dbxref_id from dbxref where accession='pub type:thesis'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:unpublished');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'unpublished',(select dbxref_id from dbxref where accession='pub type:unpublished'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:video');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'video',(select dbxref_id from dbxref where accession='pub type:video'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:paper');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'paper',(select dbxref_id from dbxref where accession='pub type:paper'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:journal');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'journal',(select dbxref_id from dbxref where accession='pub type:journal'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:null pub');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'null pub',(select dbxref_id from dbxref where accession='pub type:null pub'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:submitted');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'submitted',(select dbxref_id from dbxref where accession='pub type:submitted'));
INSERT INTO cv (name) VALUES ('pub relationship type');
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub relationship type:also_in');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub relationship type'),'also_in',(select dbxref_id from dbxref where accession='pub relationship type:also_in'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub relationship type:corrects');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub relationship type'),'corrects',(select dbxref_id from dbxref where accession='pub relationship type:corrects'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub relationship type:makes_obsolete');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub relationship type'),'makes_obsolete',(select dbxref_id from dbxref where accession='pub relationship type:makes_obsolete'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub relationship type:published_in');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub relationship type'),'published_in',(select dbxref_id from dbxref where accession='pub relationship type:published_in'));
INSERT INTO cv (name) VALUES ('pubprop type');
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:abbreviation');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'abbreviation',(select dbxref_id from dbxref where accession='pubprop type:abbreviation'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:abstract');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'abstract',(select dbxref_id from dbxref where accession='pubprop type:abstract'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:abstract_languages');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'abstract_languages',(select dbxref_id from dbxref where accession='pubprop type:abstract_languages'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:cam_offprint');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'cam_offprint',(select dbxref_id from dbxref where accession='pubprop type:cam_offprint'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:comment');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'comment',(select dbxref_id from dbxref where accession='pubprop type:comment'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:errata');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'errata',(select dbxref_id from dbxref where accession='pubprop type:errata'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:erratum');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'erratum',(select dbxref_id from dbxref where accession='pubprop type:erratum'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:internalnotes');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'internalnotes',(select dbxref_id from dbxref where accession='pubprop type:internalnotes'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:languages');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'languages',(select dbxref_id from dbxref where accession='pubprop type:languages'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:series_abbrev');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'series_abbrev',(select dbxref_id from dbxref where accession='pubprop type:series_abbrev'));
INSERT INTO cv (name) VALUES ('apollo');
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'apollo:suffix');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='apollo'),'suffix',(select dbxref_id from dbxref where accession='apollo:suffix'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'apollo:prefix');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='apollo'),'prefix',(select dbxref_id from dbxref where accession='apollo:prefix'));
