INSERT INTO cv (name) VALUES ('property type');
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:aminoacid');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'aminoacid',(select dbxref_id from dbxref where accession='property type:aminoacid'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:anticodon');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'anticodon',(select dbxref_id from dbxref where accession='property type:anticodon'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:comment');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'comment',(select dbxref_id from dbxref where accession='property type:comment'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:date');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'date',(select dbxref_id from dbxref where accession='property type:date'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:description');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'description',(select dbxref_id from dbxref where accession='property type:description'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:element');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'element',(select dbxref_id from dbxref where accession='property type:element'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:encoded_symbol');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'encoded_symbol',(select dbxref_id from dbxref where accession='property type:encoded_symbol'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:internal_synonym');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'internal_synonym',(select dbxref_id from dbxref where accession='property type:internal_synonym'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:owner');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'owner',(select dbxref_id from dbxref where accession='property type:owner'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:problem');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'problem',(select dbxref_id from dbxref where accession='property type:problem'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:protein_id');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'protein_id',(select dbxref_id from dbxref where accession='property type:protein_id'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:qseq_type');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'qseq_type',(select dbxref_id from dbxref where accession='property type:qseq_type'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:sp_comment');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'sp_comment',(select dbxref_id from dbxref where accession='property type:sp_comment'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:sp_status');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'sp_status',(select dbxref_id from dbxref where accession='property type:sp_status'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:status');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'status',(select dbxref_id from dbxref where accession='property type:status'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:symbol');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'symbol',(select dbxref_id from dbxref where accession='property type:symbol'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:unixdate');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'unixdate',(select dbxref_id from dbxref where accession='property type:unixdate'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:gbunit');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'gbunit',(select dbxref_id from dbxref where accession='property type:gbunit'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:cyto_range');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'cyto_range',(select dbxref_id from dbxref where accession='property type:cyto_range'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:dicistronic');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'dicistronic',(select dbxref_id from dbxref where accession='property type:dicistronic'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:validation_flag');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'validation_flag',(select dbxref_id from dbxref where accession='property type:validation_flag'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:keywords');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'keywords',(select dbxref_id from dbxref where accession='property type:keywords'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:organism');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'organism',(select dbxref_id from dbxref where accession='property type:organism'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:mol_type');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'mol_type',(select dbxref_id from dbxref where accession='property type:mol_type'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:dev_stage');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'dev_stage',(select dbxref_id from dbxref where accession='property type:dev_stage'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:chromosome');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'chromosome',(select dbxref_id from dbxref where accession='property type:chromosome'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'property type:map');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='property type'),'map',(select dbxref_id from dbxref where accession='property type:map'));
INSERT INTO cv (name) VALUES ('pub type');
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:computer file');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'computer file',(select dbxref_id from dbxref where accession='pub type:computer file'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:curator');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'curator',(select dbxref_id from dbxref where accession='pub type:curator'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:publication');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'publication',(select dbxref_id from dbxref where accession='pub type:publication'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:Book');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'Book',(select dbxref_id from dbxref where accession='pub type:Book'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:DNA/RNA sequence record');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'DNA/RNA sequence record',(select dbxref_id from dbxref where accession='pub type:DNA/RNA sequence record'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:abstract');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'abstract',(select dbxref_id from dbxref where accession='pub type:abstract'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:archive');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'archive',(select dbxref_id from dbxref where accession='pub type:archive'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:automatic genome annotation');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'automatic genome annotation',(select dbxref_id from dbxref where accession='pub type:automatic genome annotation'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:bibliographic list');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'bibliographic list',(select dbxref_id from dbxref where accession='pub type:bibliographic list'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:biography');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'biography',(select dbxref_id from dbxref where accession='pub type:biography'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:book');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'book',(select dbxref_id from dbxref where accession='pub type:book'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:book review');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'book review',(select dbxref_id from dbxref where accession='pub type:book review'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:booklet');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'booklet',(select dbxref_id from dbxref where accession='pub type:booklet'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:conference report');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'conference report',(select dbxref_id from dbxref where accession='pub type:conference report'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:curated genome annotation');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'curated genome annotation',(select dbxref_id from dbxref where accession='pub type:curated genome annotation'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:demonstration');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'demonstration',(select dbxref_id from dbxref where accession='pub type:demonstration'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:editorial');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'editorial',(select dbxref_id from dbxref where accession='pub type:editorial'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:erratum');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'erratum',(select dbxref_id from dbxref where accession='pub type:erratum'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:film');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'film',(select dbxref_id from dbxref where accession='pub type:film'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:interview');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'interview',(select dbxref_id from dbxref where accession='pub type:interview'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:jigsaw puzzle');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'jigsaw puzzle',(select dbxref_id from dbxref where accession='pub type:jigsaw puzzle'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:letter');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'letter',(select dbxref_id from dbxref where accession='pub type:letter'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:meeting report');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'meeting report',(select dbxref_id from dbxref where accession='pub type:meeting report'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:microfiche');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'microfiche',(select dbxref_id from dbxref where accession='pub type:microfiche'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:microscope slides');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'microscope slides',(select dbxref_id from dbxref where accession='pub type:microscope slides'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:news article');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'news article',(select dbxref_id from dbxref where accession='pub type:news article'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:note');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'note',(select dbxref_id from dbxref where accession='pub type:note'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:obituary');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'obituary',(select dbxref_id from dbxref where accession='pub type:obituary'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:other');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'other',(select dbxref_id from dbxref where accession='pub type:other'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:patent');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'patent',(select dbxref_id from dbxref where accession='pub type:patent'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:personal communication');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'personal communication',(select dbxref_id from dbxref where accession='pub type:personal communication'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:poem');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'poem',(select dbxref_id from dbxref where accession='pub type:poem'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:press release');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'press release',(select dbxref_id from dbxref where accession='pub type:press release'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:protein sequence record');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'protein sequence record',(select dbxref_id from dbxref where accession='pub type:protein sequence record'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:recording');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'recording',(select dbxref_id from dbxref where accession='pub type:recording'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:retraction');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'retraction',(select dbxref_id from dbxref where accession='pub type:retraction'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:review');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'review',(select dbxref_id from dbxref where accession='pub type:review'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:slides');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'slides',(select dbxref_id from dbxref where accession='pub type:slides'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:spoof');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'spoof',(select dbxref_id from dbxref where accession='pub type:spoof'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:stock list');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'stock list',(select dbxref_id from dbxref where accession='pub type:stock list'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:supplementary material');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'supplementary material',(select dbxref_id from dbxref where accession='pub type:supplementary material'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:tactile diagram');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'tactile diagram',(select dbxref_id from dbxref where accession='pub type:tactile diagram'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:teaching note');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'teaching note',(select dbxref_id from dbxref where accession='pub type:teaching note'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:thesis');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'thesis',(select dbxref_id from dbxref where accession='pub type:thesis'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:unpublished');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'unpublished',(select dbxref_id from dbxref where accession='pub type:unpublished'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:video');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'video',(select dbxref_id from dbxref where accession='pub type:video'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:paper');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'paper',(select dbxref_id from dbxref where accession='pub type:paper'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:journal');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'journal',(select dbxref_id from dbxref where accession='pub type:journal'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:null pub');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'null pub',(select dbxref_id from dbxref where accession='pub type:null pub'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub type:submitted');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub type'),'submitted',(select dbxref_id from dbxref where accession='pub type:submitted'));
INSERT INTO cv (name) VALUES ('pub relationship type');
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub relationship type:also_in');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub relationship type'),'also_in',(select dbxref_id from dbxref where accession='pub relationship type:also_in'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub relationship type:corrects');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub relationship type'),'corrects',(select dbxref_id from dbxref where accession='pub relationship type:corrects'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub relationship type:makes_obsolete');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub relationship type'),'makes_obsolete',(select dbxref_id from dbxref where accession='pub relationship type:makes_obsolete'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pub relationship type:published_in');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pub relationship type'),'published_in',(select dbxref_id from dbxref where accession='pub relationship type:published_in'));
INSERT INTO cv (name) VALUES ('pubprop type');
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:abbreviation');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'abbreviation',(select dbxref_id from dbxref where accession='pubprop type:abbreviation'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:abstract');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'abstract',(select dbxref_id from dbxref where accession='pubprop type:abstract'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:abstract_languages');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'abstract_languages',(select dbxref_id from dbxref where accession='pubprop type:abstract_languages'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:cam_offprint');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'cam_offprint',(select dbxref_id from dbxref where accession='pubprop type:cam_offprint'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:comment');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'comment',(select dbxref_id from dbxref where accession='pubprop type:comment'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:errata');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'errata',(select dbxref_id from dbxref where accession='pubprop type:errata'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:erratum');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'erratum',(select dbxref_id from dbxref where accession='pubprop type:erratum'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:internalnotes');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'internalnotes',(select dbxref_id from dbxref where accession='pubprop type:internalnotes'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:languages');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'languages',(select dbxref_id from dbxref where accession='pubprop type:languages'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'pubprop type:series_abbrev');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='pubprop type'),'series_abbrev',(select dbxref_id from dbxref where accession='pubprop type:series_abbrev'));
INSERT INTO cv (name) VALUES ('apollo');
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'apollo:suffix');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='apollo'),'suffix',(select dbxref_id from dbxref where accession='apollo:suffix'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'apollo:prefix');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((select cv_id from cv where name='apollo'),'prefix',(select dbxref_id from dbxref where accession='apollo:prefix'));
INSERT INTO dbxref (db_id,accession) VALUES ((select db_id from db where name='null'), 'apollo:producedby');
INSERT INTO cvterm (cv_id,name,dbxref_id,is_relationshiptype) VALUES ((select cv_id from cv where name='apollo'),'producedby',(select dbxref_id from dbxref where accession='apollo:producedby'),1);
